#!/usr/bin/env bash
# Build BenchGraph.app — a double-clickable macOS app bundle.
#
# SwiftPM produces a bare executable; this wraps it in the .app bundle layout
# macOS needs (Info.plist + Contents/MacOS) so it launches from Finder, and it
# registers the .benchgraph document type so projects open on double-click.
#
# Distribution (Developer ID signing + notarization + DMG) is opt-in via
# environment variables so a plain local build still works with no Apple account:
#
#   DEVELOPER_ID_APP   e.g. "Developer ID Application: Jane Roe (TEAMID)"
#                      When set, the app is signed with the hardened runtime.
#                      When unset, the app is ad-hoc signed (local runs only).
#   NOTARY_PROFILE     A `notarytool` keychain profile name. When set (and a DMG
#                      is built), the DMG is submitted for notarization + stapled.
#   MAKE_DMG=1         Also package a distributable BenchGraph.dmg.
#
# Examples:
#   ./scripts/build-app.sh                      # local ad-hoc build
#   DEVELOPER_ID_APP="Developer ID Application: Jane Roe (AB12CD34EF)" \
#     MAKE_DMG=1 NOTARY_PROFILE=benchgraph ./scripts/build-app.sh
set -euo pipefail

CONFIG="${1:-release}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/BenchGraph.app"
DMG="$ROOT/BenchGraph.dmg"
VERSION="0.1.0"
BUNDLE_ID="com.benchgraph.app"
UTI="com.benchgraph.project"

echo "Building BenchGraphApp ($CONFIG)..."
swift build -c "$CONFIG" --product BenchGraphApp

BIN="$ROOT/.build/$CONFIG/BenchGraphApp"
[[ -x "$BIN" ]] || { echo "error: built binary not found at $BIN"; exit 1; }

echo "Assembling $APP..."
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/BenchGraph"

# App + document icon (generated by scripts/make-icon.swift; see assets/).
if [[ -f "$ROOT/assets/AppIcon.icns" ]]; then
    cp "$ROOT/assets/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>             <string>BenchGraph</string>
    <key>CFBundleDisplayName</key>      <string>BenchGraph</string>
    <key>CFBundleIdentifier</key>       <string>${BUNDLE_ID}</string>
    <key>CFBundleVersion</key>          <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundlePackageType</key>      <string>APPL</string>
    <key>CFBundleExecutable</key>       <string>BenchGraph</string>
    <key>LSMinimumSystemVersion</key>   <string>13.0</string>
    <key>NSHighResolutionCapable</key>  <true/>
    <key>NSPrincipalClass</key>         <string>NSApplication</string>
    <key>CFBundleIconFile</key>         <string>AppIcon</string>

    <!-- Own the .benchgraph project document so Finder opens it with this app. -->
    <key>CFBundleDocumentTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeName</key>      <string>BenchGraph Project</string>
            <key>CFBundleTypeRole</key>      <string>Editor</string>
            <key>LSHandlerRank</key>         <string>Owner</string>
            <key>CFBundleTypeIconFile</key>  <string>AppIcon</string>
            <key>LSItemContentTypes</key>
            <array><string>${UTI}</string></array>
        </dict>
    </array>
    <key>UTExportedTypeDeclarations</key>
    <array>
        <dict>
            <key>UTTypeIdentifier</key>      <string>${UTI}</string>
            <key>UTTypeDescription</key>     <string>BenchGraph Project</string>
            <key>UTTypeConformsTo</key>
            <array>
                <string>public.json</string>
                <string>public.data</string>
            </array>
            <key>UTTypeTagSpecification</key>
            <dict>
                <key>public.filename-extension</key>
                <array><string>benchgraph</string></array>
            </dict>
        </dict>
    </array>
</dict>
</plist>
PLIST

# Hardened-runtime entitlements (used only for a Developer ID signed build).
ENTITLEMENTS="$(mktemp -t benchgraph-entitlements).plist"
cat > "$ENTITLEMENTS" <<'ENT'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>       <false/>
    <key>com.apple.security.cs.allow-jit</key>      <false/>
</dict>
</plist>
ENT

if [[ -n "${DEVELOPER_ID_APP:-}" ]]; then
    echo "Signing with Developer ID: $DEVELOPER_ID_APP (hardened runtime)..."
    codesign --force --deep --timestamp --options runtime \
        --entitlements "$ENTITLEMENTS" \
        --sign "$DEVELOPER_ID_APP" "$APP"
    codesign --verify --strict --verbose=2 "$APP"
else
    echo "No DEVELOPER_ID_APP set — ad-hoc signing (local runs only)..."
    codesign --force --deep --sign - "$APP" 2>/dev/null || \
        echo "note: ad-hoc codesign skipped (codesign unavailable)"
fi
rm -f "$ENTITLEMENTS"

echo "Done: $APP"
echo "Launch it with:  open \"$APP\"    (or double-click in Finder)"

# --- Optional DMG packaging + notarization ------------------------------------

if [[ "${MAKE_DMG:-0}" == "1" ]]; then
    echo "Packaging $DMG..."
    rm -f "$DMG"
    STAGE="$(mktemp -d)"
    cp -R "$APP" "$STAGE/"
    ln -s /Applications "$STAGE/Applications"
    hdiutil create -volname "BenchGraph" -srcfolder "$STAGE" -ov -format UDZO "$DMG" >/dev/null
    rm -rf "$STAGE"
    echo "Done: $DMG"

    if [[ -n "${DEVELOPER_ID_APP:-}" ]]; then
        codesign --force --sign "$DEVELOPER_ID_APP" "$DMG"
    fi

    if [[ -n "${NOTARY_PROFILE:-}" ]]; then
        echo "Submitting $DMG for notarization (profile: $NOTARY_PROFILE)..."
        xcrun notarytool submit "$DMG" --keychain-profile "$NOTARY_PROFILE" --wait
        echo "Stapling notarization ticket..."
        xcrun stapler staple "$DMG"
        xcrun stapler validate "$DMG"
    else
        echo "note: NOTARY_PROFILE unset — DMG built but not notarized."
        echo "      Set up once with: xcrun notarytool store-credentials <profile> \\"
        echo "        --apple-id <email> --team-id <TEAMID> --password <app-specific-pw>"
    fi
fi
